# Generated by Django 3.0.6 on 2020-06-27 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AlumnoHorario',
            fields=[
                ('id_alum_horario', models.AutoField(primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Alumno')),
            ],
            options={
                'verbose_name': 'Alumno Horario',
                'ordering': ['id_alum_horario'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('clave_empleado', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Estado')),
            ],
            options={
                'verbose_name': 'Profesores',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClaseHorario',
            fields=[
                ('id_clase_horario', models.AutoField(primary_key=True, serialize=False)),
                ('lun_ini', models.TimeField(blank=True, null=True)),
                ('lun_fin', models.TimeField(blank=True, null=True)),
                ('mar_ini', models.TimeField(blank=True, null=True)),
                ('mar_fin', models.TimeField(blank=True, null=True)),
                ('mie_ini', models.TimeField(blank=True, null=True)),
                ('mie_fin', models.TimeField(blank=True, null=True)),
                ('jue_ini', models.TimeField(blank=True, null=True)),
                ('jue_fin', models.TimeField(blank=True, null=True)),
                ('vie_ini', models.TimeField(blank=True, null=True)),
                ('vie_fin', models.TimeField(blank=True, null=True)),
                ('sab_ini', models.TimeField(blank=True, null=True)),
                ('sab_fin', models.TimeField(blank=True, null=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Estado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profesor')),
            ],
            options={
                'verbose_name': 'Clase horarios',
                'ordering': ['id_clase_horario'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('clave_carrera', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('materias', models.ManyToManyField(help_text='Seleccione las materias', to='api.Materia')),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('no_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True)),
                ('hora_entrada', models.TimeField(blank=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('puntualidad', models.TextField(blank=True, max_length=1, null=True)),
                ('alumno_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AlumnoHorario')),
            ],
            options={
                'ordering': ['no_asistencia'],
            },
        ),
        migrations.AddField(
            model_name='alumnohorario',
            name='clase_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ClaseHorario'),
        ),
        migrations.AddField(
            model_name='alumnohorario',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Estado'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Estado'),
        ),
    ]
