# Generated by Django 3.0.6 on 2020-06-27 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['nombre', 'apellidos']},
        ),
        migrations.AlterModelOptions(
            name='clasehorario',
            options={'ordering': ['id_clase_horario'], 'verbose_name': 'Clase horario'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['nombre', 'apellidos'], 'verbose_name': 'Maestro'},
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('alumno_horario', 'fecha')},
        ),
    ]
