# Generated by Django 3.0.6 on 2020-06-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200627_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='puntualidad',
            field=models.BooleanField(blank=True, max_length=1, null=True),
        ),
    ]
