# Generated by Django 3.0.6 on 2020-06-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200627_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['nombre', 'apellidos'], 'permissions': [('es_alumno', 'Es alumno')]},
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-no_asistencia']},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['nombre', 'apellidos'], 'permissions': [('es_maestro', 'Es maestro')], 'verbose_name': 'Maestro'},
        ),
    ]
