# Generated by Django 3.0.6 on 2020-06-30 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200629_1700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alumnohorario',
            unique_together={('alumno', 'clase_horario')},
        ),
    ]
