# Generated by Django 3.0.6 on 2020-07-22 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200629_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('clave_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Carrera')),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='alumnohorario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='clasehorario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='estado',
        ),
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumnohorario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clasehorario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.AddField(
            model_name='clasehorario',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Grupo'),
        ),
    ]
