# Generated by Django 3.0.6 on 2020-07-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200722_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='clave_carrera',
            new_name='carrera',
        ),
    ]
