# Generated by Django 3.0.6 on 2020-07-24 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200722_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnohorario',
            options={'ordering': ['clase_horario', 'alumno'], 'verbose_name': 'Alumno Horario'},
        ),
        migrations.AddField(
            model_name='asistencia',
            name='clase_horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ClaseHorario'),
        ),
        migrations.AlterField(
            model_name='clasehorario',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Grupo'),
        ),
    ]
