# Generated by Django 3.0.6 on 2020-07-24 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200723_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='clase_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ClaseHorario'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
